name: Build and Upload App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Set execute permissions on gradlew
          run: chmod +x ./gradlew
        - name: Build with Gradle
          run: ./gradlew build
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: true
            prerelease: true
        - name: Upload APK
          uses: actions/upload-release-asset@v1
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: app/build/outputs/apk/release/app-release.apk
            asset_name: app-release ${{ github.ref }}.apk
            asset_content_type: application/vnd.android.package-archive