name: Build and Upload App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            distribution: 'adopt'  # 使用AdoptOpenJDK发行版
            java-version: '17'  # 设置Java版本为17
        - name: Set execute permissions on gradlew
          run: chmod +x ./gradlew
        - name: Build with Gradle
          run: ./gradlew build
        - name: Create Release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # 使用存储在仓库中的GITHUB_TOKEN secret
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: true
            prerelease: true
        - name: Upload APK
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: app/build/outputs/apk/debug/app-debug.apk
            asset_name: app-release ${{ github.ref }}.apk
            asset_content_type: application/vnd.android.package-archive
